In [ ]:
import numpy as np

In [ ]:
# np.arange(1,10+1) #it will create a one direction array
# np.arange(1,10+1).reshape(2,5) # it will create two dimension array
np.arange(0.,11,0.5) # we can provide float numbers in arange function


array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [ ]:
arr4 = np.linspace(1,10)
arr4

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
np.zeros((2,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
a  = np.random.randint(1,10,6).reshape((2,3))
a

array([[6, 3, 9],
       [6, 7, 2]])

In [ ]:
b = np.random.randn(50)
b

array([-2.29580938,  1.31253167, -1.68779468, -0.41627778, -1.46162386,
       -0.46870202, -1.34446264,  0.02819688, -1.20559257, -0.61322357,
        0.58208355,  1.10705536,  1.5311999 ,  1.35932411, -2.43997496,
       -1.24208337,  0.34359605,  0.53361493,  0.16036378,  2.33821956,
        0.52887462,  0.16290469, -0.75776505, -0.4041901 ,  0.22137066,
        0.71556029, -0.35545533,  0.68014822,  0.17194445,  1.20827504,
       -0.82069439, -0.14765477, -0.13575821, -2.2388465 , -1.96965386,
       -1.36915615, -0.86726129,  0.14326934,  0.68080598,  1.23054571,
        1.38378866,  0.65961935, -2.16074095,  0.33035464,  0.84196935,
        0.8478165 ,  0.19538974,  0.53857491,  0.89120872, -2.35723301])

In [ ]:
c = np.random.rand(5)
c

array([0.98740058, 0.42365172, 0.65531847, 0.67789638, 0.47964458])

In [ ]:
d = np.array(['mitesh','hardik','khush','anand','abhishek','anas','vinit'])
# np.random.choice(d)
inde = np.random.randint(0,len(d)+1,1)
d[inde]

array(['anas'], dtype='<U8')

In [ ]:
np.random.shuffle(d)
d

array(['anand', 'abhishek', 'anas', 'khush', 'vinit', 'hardik', 'mitesh'],
      dtype='<U8')

In [ ]:
from sys import prefix
e = d
print(d)
print(e)
e[3]=10
print(d)
print(e)


['anand' 'abhishek' 'anas' 'khush' 'vinit' 'hardik' 'mitesh']
['anand' 'abhishek' 'anas' 'khush' 'vinit' 'hardik' 'mitesh']
['anand' 'abhishek' 'anas' '10' 'vinit' 'hardik' 'mitesh']
['anand' 'abhishek' 'anas' '10' 'vinit' 'hardik' 'mitesh']


In [ ]:
e = np.copy(d)
e
print(d)
print(e)
e[2]=5
print(d)
print(e)

['anand' 'abhishek' 'anas' '10' 'vinit' 'hardik' 'mitesh']
['anand' 'abhishek' 'anas' '10' 'vinit' 'hardik' 'mitesh']
['anand' 'abhishek' 'anas' '10' 'vinit' 'hardik' 'mitesh']
['anand' 'abhishek' '5' '10' 'vinit' 'hardik' 'mitesh']


In [ ]:
arr9 = np.arange(0,100,3)
arr9[9]

np.int64(27)

In [18]:
arr11 = np.array([1,2,3])
arr12 = np.array([4,3,2])
# arr11+arr12 array([5, 5, 5])
# arr11-arr12  array([-3, -1,  1])
# arr11*arr12  array([4, 6, 6])


array([4, 6, 6])

In [19]:
arr11

array([1, 2, 3])

In [29]:
arr11 >


array([False, False, False])

In [35]:
arr20 =  np.array([78,65,86,5,21,45,20])
# arr>80
np.modf(arr20)


(array([0., 0., 0., 0., 0., 0., 0.]),
 array([78., 65., 86.,  5., 21., 45., 20.]))

In [60]:
arr21 = np.arange(1,21).reshape(2,2,5)
arr21

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [68]:
arr21[0:1,0:1,2:]

array([[[3, 4, 5]]])