# **numnpy**
numerical python
We mainly use this to create and work with it.
It used in data creatoion and manipulation.


In [1]:
import numpy as np
a = [1,2,3]
b = np.array(a)
b


array([1, 2, 3])

In [2]:
np.__version__

'2.0.2'

There are 3 types of array

1. Unidimension Array
2. Bidimensional ARRAY
3. MULTIDIMENSION ARRAY

In [8]:
# Unidimension Array
arr2 = np.array(((1,2),(3,4),(5,6)))
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
# Multidimensional Array
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
arr3.ndim

3

In [14]:
arr3
arr3.reshape(3,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])