In [ ]:
import numpy as np


In [ ]:
# A 1D array of 10 equally spaced values between 0 and 50.
arr1 = np.linspace(0,50,10)
arr1

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [ ]:
# A 2D array of shape (3x3) containing random integers between 5 and 20.
arr2 = np.random.randint(5,20,9).reshape(3,3)
arr2


array([[14, 16, 13],
       [ 9, 11, 15],
       [19,  7,  9]])

In [ ]:
# Print the dimensions of both arrays.
print("Dimension of array1 is: ",arr1.ndim)
print("Dimension of array2 is: ",arr2.ndim)


Dimension of array1 is:  1
Dimension of array2 is:  2


In [ ]:
# Print the shape of both arrays.
print("Shape of array1 is: ",arr1.shape)
print("Shape of array2 is: ",arr2.shape)


Shape of array1 is:  (10,)
Shape of array2 is:  (3, 3)


In [ ]:
# Reshape the 1D array into a 2D array with shape (2x5).
arr1 = arr1.reshape(2,5)
# Print the reshaped array.
print(arr1)
# Flatten the reshaped array back to 1D and print it
arr1 = arr1.reshape(-1)
print("Flatten array is: ",arr1)

[[ 0.          5.55555556 11.11111111 16.66666667 22.22222222]
 [27.77777778 33.33333333 38.88888889 44.44444444 50.        ]]
Flatten array is:  [ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [ ]:
# For the 2D array created in Part 1, print the element present at the 2nd row and 3rd column.
print(arr2[1,2])
# Extract the first two rows and the last two columns of the array.
print(arr2[0:2,1:])

15
[[16 13]
 [11 15]]


In [ ]:
# Slice the first four elements from the flattened 1D array
print(arr1[0:4])
# Reverse the elements of the 1D array using slicing.
print(arr1[::-1])

[ 0.          5.55555556 11.11111111 16.66666667]
[50.         44.44444444 38.88888889 33.33333333 27.77777778 22.22222222
 16.66666667 11.11111111  5.55555556  0.        ]


In [ ]:
# Create another 1D array of 10 integers between 1 and 10
arr3 = np.arange(1,11)
# Perform the following element-wise operations between the 1D arrays created in Part 1 and Part 3:
# Addition
print(arr1+arr3)
# Multiplication
print(arr1*arr3)
# Subtract a constant value (e.g., 5) from the array.
print(arr1/5)



[ 1.          7.55555556 14.11111111 20.66666667 27.22222222 33.77777778
 40.33333333 46.88888889 53.44444444 60.        ]
[  0.          11.11111111  33.33333333  66.66666667 111.11111111
 166.66666667 233.33333333 311.11111111 400.         500.        ]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [ ]:
# Create a 1D array of 5 random values between 0 and 1.
arr4 = np.random.rand(5)
arr4
# Create another 1D array of 5 random values between -1 and 1.
arr5 = np.random.randint(-1,2,5)
arr5

array([ 0, -1,  0,  0,  1])

In [ ]:
# Create a copy of the original 2D array from Part 1.
arr6 = np.copy(arr2)
arr6
# Modify one element in the copy and show that it doesn’t affect the original array.
arr6[1][1] =10
print(arr2)
print(arr6)

# Create a view of the original 2D array and modify one element. Show that it does affect the original array.
arr7 = arr2.view()
arr7[0,2]=165
print(arr2)
print(arr7)

# In summary copy will not  affect the original array but view will affect

[[ 14  16 165]
 [  9  11  15]
 [ 19   7   9]]
[[ 14  16 165]
 [  9  10  15]
 [ 19   7   9]]
[[ 14  16 165]
 [  9  11  15]
 [ 19   7   9]]
[[ 14  16 165]
 [  9  11  15]
 [ 19   7   9]]


In [ ]:
# Write a program that asks the user to input a number (n), and then generates an n x n array of random integers between 1 and 100.5
n = int(input("Enter n: "))
# print(n)
bonus_array = np.random.randint(1,101,n*n).reshape(n,n)
# Find the sum of all the elements in the array and print the result.
bonus_array.sum()

Enter n: 5


np.int64(1213)